### ISSUE TITLE
Getting Argument error

### ISSUE THREAD

**Issue by tarakaprabhuchinta** [github-developer/github-app-template#11]
When I try to follow the tutorial to setup development environment, Im getting the following error`/usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann/regular.rb:22:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `new'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `block in new'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann/equality_map.rb:43:in `fetch'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann/pattern.rb:59:in `new'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann.rb:67:in `new'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann.rb:70:in `block in new'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann.rb:70:in `map'
	from /usr/local/lib/ruby/gems/3.1.0/gems/mustermann-1.0.3/lib/mustermann.rb:70:in `new'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1641:in `compile'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1629:in `compile!'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1271:in `error'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1838:in `<class:Base>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:894:in `<module:Sinatra>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:22:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/main.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra/main.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra.rb:1:in `require'
	from /usr/local/lib/ruby/gems/3.1.0/gems/sinatra-2.0.4/lib/sinatra.rb:1:in `<top (required)>'
	from template_server.rb:1:in `require'
	from template_server.rb:1:in `<main>'`

**Comment by guenjun** [comment]
This error can be fixed by the [PR#14](https://github.com/github-developer/github-app-template/pull/14).
