### ISSUE TITLE
Run the template error：uninitialized constant Faraday

### ISSUE THREAD

**Issue by shiyuhang0** [github-developer/github-app-template#27]
Follow this guide https://docs.github.com/en/developers/apps/getting-started-with-apps/setting-up-your-development-environment-to-create-a-github-app and get error in step 6

```
➜  github-app-template git:(master) ✗ bundle exec ruby template_server.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/go/bin in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/go/bin in PATH, mode 040777
Traceback (most recent call last):
        8: from template_server.rb:2:in `<main>'
        7: from template_server.rb:2:in `require'
        6: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.13.0/lib/octokit.rb:4:in `<top (required)>'
        5: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.13.0/lib/octokit.rb:4:in `require'
        4: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.13.0/lib/octokit/default.rb:1:in `<top (required)>'
        3: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.13.0/lib/octokit/default.rb:1:in `require'
        2: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
        1: from /Library/Ruby/Gems/2.6.0/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/Library/Ruby/Gems/2.6.0/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError (NameError)
Did you mean?  Faraday::ClientError

```

**Comment by asterwyx** [comment]
I've also got this error. It seems like that modify Faraday::Error::ClientError to Faraday::ClientError will solve this problem, but I don't think this is a correct action.
